import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'sw' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    'my_orders': 'My Orders',
    'edit_profile': 'Edit Profile',
    'chat': 'Chat',
    'address': 'Address',
    'change_password': 'Change Password',
    'change_language': 'Change Language',
    'sign_out': 'Sign Out',
    'active_orders': 'Active Orders',
    'previous_orders': 'Previous Orders',
    'order_id': 'Order ID',
    'total': 'Total',
    'see_details': 'See Details',
    'back_to_home': 'Back to Home',
    'back_to_orders': 'Back to Orders',
    'order_details': 'Order Details',
    'order_type': 'Order Type',
    'delivery_time': 'Delivery Time',
    'takeaway_time': 'Takeaway Time',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'delivery_charge': 'Delivery Charge',
    'print_invoice': 'Print Invoice',
    'pay_now': 'Pay Now',
    'status': 'Status',
    'method': 'Method',
    'payment_info': 'Payment Info',
    'delivery_address': 'Delivery Address',
    'save': 'Save',
    'cancel': 'Cancel',
    'email': 'Email',
    'phone': 'Phone Number',
    'joined': 'Joined',
    'personal_info': 'Personal Information',
    'edit': 'Edit',
    'welcome_back': 'Welcome Back!',
    'sign_in_subtitle': 'Sign in to your account',
    'or': 'OR',
    'continue_with_google': 'Continue with Google',
    'dont_have_account': "Don't have an account?",
    'sign_up': 'Sign up',
    'password': 'Password',
    'forgot_password': 'Forgot Password?',
    'sign_in': 'Sign In',
    'new_password': 'New Password',
    'confirm_password': 'Confirm Password',
    'update_password': 'Update Password',
    'chat_placeholder': 'Type a message...',
    'send': 'Send',
    'food': 'Food',
    'grocery': 'Grocery',
    'pharmacy': 'Pharmacy',
    'ecommerce': 'eCommerce',
    'taxi': 'Taxi',
    'parcel': 'Parcel',
    'salons': 'Salons',
    'hotels': 'Hotels',
    'welcome': 'Welcome',
    'businesses': 'Businesses',
    'products': 'Products',
    'search_placeholder': 'Search for items...',
    'invalid_email_or_password': 'Invalid email or password.',
    'auth_disabled_instructions': "Email registration is currently disabled. Please enable 'Email/Password' in your Firebase Console Authentication settings.",
    'login_failed': 'Login failed. Please try again.',
    'signup_failed': 'Registration failed. Please try again.',
    'passwords_dont_match': 'Passwords do not match!',
    'agree_to_terms_error': 'Please agree to the terms and conditions',
    'account_created_success': 'Account created successfully!',
    'registration_submitted': 'Registration submitted for approval!',
    'nearby_stores': 'Nearby Stores',
    'see_all': 'See All',
    'other_services': 'Other Services',
    'popular_restaurants': 'Popular Restaurants',
    'popular_products': 'Popular Products',
    'view_all': 'View All',
    'order': 'Order',
    'order_now': 'Order Now',
    'very_close': 'Very Close',
    'close': 'Close',
    'far_bit': 'A bit far',
    'far': 'Far',
    'extremely_far': 'Very far',
    'admin_control_panel': 'Control Panel',
    'admin_overview': 'Overview',
    'admin_businesses': 'Businesses',
    'admin_products': 'Inventory',
    'admin_communities': 'Communities',
    'admin_sales_feed': 'Sales Feed',
    'admin_marketing': 'Marketing',
    'admin_broadcast': 'Broadcast',
    'admin_gross_volume': 'Gross Volume',
    'admin_commission': 'Est. Commission',
    'admin_fees': 'Calculated Fees',
    'admin_total_sales': 'Total Sales',
    'admin_view_store': 'View Store',
    'admin_approve': 'Approve',
    'admin_reject': 'Reject',
    'admin_block': 'Block',
    'admin_delete': 'Delete',
    'admin_search_placeholder': 'Search here...',
    'admin_inventory_oversight': 'Inventory Oversight',
    'admin_members_search_placeholder': 'Search members by name or email...',
    'admin_total_members': 'Total Members',
    'admin_identity': 'Identity',
    'admin_role': 'Role',
    'admin_status': 'Status',
    'admin_interactions': 'Interactions',
    'admin_global_live_feed': 'Global Live Feed',
    'admin_live_monitoring': 'Live Monitoring',
    'admin_order_ref': 'Order Ref',
    'admin_merchant': 'Merchant',
    'admin_payment': 'Payment',
    'admin_value': 'Value',
    'admin_manage_banners': 'Manage Banners',
    'admin_add_banner': 'Add Banner',
    'admin_new_banner': 'New Promotional Banner',
    'admin_title': 'Title',
    'admin_subtitle': 'Subtitle',
    'admin_image_url': 'Image URL',
    'admin_save_banner': 'Save Banner',
    'admin_manage_coupons': 'Manage Coupons',
    'admin_add_coupon': 'Add Coupon',
    'admin_official_coupon': 'Official Coupon',
    'admin_off': 'Off',
    'admin_broadcast_title': 'Global Broadcast',
    'admin_broadcast_subtitle': 'Reach every user in your community instantly.',
    'admin_alert_title': 'Alert Title',
    'admin_alert_content': 'Alert Content',
    'admin_initiate_broadcast': 'Initiate Broadcast',
    'admin_settings': 'Settings',
    'admin_settings_business_info': 'Business Info',
    'admin_settings_payment': 'Payment',
    'admin_settings_vendor': 'Vendor',
    'admin_settings_order': 'Order',
    'admin_settings_refund': 'Refund',
    'admin_settings_deliveryman': 'Deliveryman',
    'admin_settings_customer': 'Customer',
    'admin_settings_maintenance_mode': 'Maintenance Mode',
    'admin_settings_basic_info': 'Basic Information',
    'admin_settings_business_name': 'Business Name',
    'admin_settings_upload_logo': 'Upload Logo',
    'admin_settings_upload_favicon': 'Upload Favicon',
    'admin_settings_save_information': 'Save Information',
    'admin_settings_general_setup': 'General Setup',
    'admin_settings_time_setup': 'Time Setup',
    'admin_settings_currency_setup': 'Currency Setup',
    'admin_settings_business_model': 'Business Model',
    'admin_settings_vendor_general_setup': 'General Setup',
    'admin_settings_vendor_general_desc': 'Manage the basic settings that control how vendors operate in your platform.',
    'admin_settings_vendor_cancel_order': 'Can A Vendor Cancel Order?',
    'admin_settings_vendor_self_reg': 'Vendor Self Registration',
    'admin_settings_vendor_gallery': 'Product Gallery',
    'admin_settings_vendor_access_prods': 'Access all products',
    'admin_settings_vendor_can_reply': 'Vendor Can Reply Review',
    'admin_settings_vendor_approval': 'Need Approval For',
    'admin_settings_vendor_approval_desc': 'If enabled this option to require admin approval for products to be displayed on the user side.',
    'admin_settings_vendor_add_prod': 'Add New Product',
    'admin_settings_vendor_edit_prod': 'Update Existing Product',
    'admin_settings_vendor_cash_ctrl': 'Cash in Hand Controls',
    'admin_settings_vendor_cash_desc': 'Setup your cash collection from here',
    'admin_settings_vendor_cash_overflow': 'Cash In Hand Overflow',
    'admin_settings_vendor_max_cash': 'Maximum Amount To Hold Cash In Hand',
    'admin_settings_vendor_min_pay': 'Minimum Amount To Pay',
    'admin_settings_order_type': 'Order Type',
    'admin_settings_order_type_desc': 'Which way customer order their food',
    'admin_settings_home_delivery': 'Home Delivery',
    'admin_settings_takeaway': 'Takeaway',
    'admin_settings_scheduled_order': 'Scheduled Order',
    'admin_settings_time_interval': 'Time Interval For Scheduled Delivery',
    'admin_settings_free_delivery': 'Free Delivery Setup',
    'admin_settings_free_delivery_desc': 'Enable this option to give customers a free delivery offer.',
    'admin_settings_extra_packaging': 'Enable Extra Packaging Charge',
    'admin_settings_extra_packaging_desc': 'Adds an extra fee for orders that need additional protection, such as fragile or bulky items.',
    'admin_settings_other_setup': 'Other Setup',
    'admin_settings_prescription_order': 'Place Order by Prescription',
    'admin_settings_delivery_verification': 'Order delivery verification',
    'admin_settings_confirm_order': 'Who Will Confirm Order',
    'admin_settings_cancellation_msg': 'Setup Order Cancellation Messages',
    'admin_settings_cancellation_msg_desc': 'Set up cancellation messages here to allow customers to select a reason when canceling an order',
    'admin_settings_cancellation_reason': 'Order Cancellation Reason',
    'admin_settings_user_type': 'User Type',
    'admin_settings_reason_list': 'Order cancellation reason list',
    'admin_settings_refund_mode': 'Refund Request Mode',
    'admin_settings_refund_mode_desc': 'Customers cannot request a refund if the admin does not specify a cause for the refund. Admin MUST provide a refund reason.',
    'admin_settings_add_refund_reason': 'Add Refund Reason',
    'admin_settings_refund_reason': 'Refund Reason',
    'admin_settings_refund_reason_list': 'Refund Reason List',
  },
  sw: {
    'my_orders': 'Oda Zangu',
    'edit_profile': 'Hariri Wasifu',
    'chat': 'Mazungumzo',
    'address': 'Anwani',
    'change_password': 'Badili Nenosiri',
    'change_language': 'Badili Lugha',
    'sign_out': 'Ondoka',
    'active_orders': 'Oda Zinazoendelea',
    'previous_orders': 'Oda Zilizopita',
    'order_id': 'Namba ya Oda',
    'total': 'Jumla',
    'see_details': 'Angalia Zaidi',
    'back_to_home': 'Rudi Nyumbani',
    'back_to_orders': 'Rudi kwenye Oda',
    'order_details': 'Maelezo ya Oda',
    'order_type': 'Aina ya Oda',
    'delivery_time': 'Muda wa Kufikishiwa',
    'takeaway_time': 'Muda wa Kuchukua',
    'subtotal': 'Jumla Ndogo',
    'discount': 'Punguzo',
    'delivery_charge': 'Gharama ya Usafiri',
    'print_invoice': 'Chapa Stakabadhi',
    'pay_now': 'Lipa Sasa',
    'status': 'Hali',
    'method': 'Njia',
    'payment_info': 'Taarifa za Malipo',
    'delivery_address': 'Anwani ya Kufikishiwa',
    'save': 'Hifadhi',
    'cancel': 'Ghairi',
    'email': 'Barua Pepe',
    'phone': 'Namba ya Simu',
    'joined': 'Umejiunga',
    'personal_info': 'Taarifa Binafsi',
    'edit': 'Hariri',
    'welcome_back': 'Karibu Tena!',
    'sign_in_subtitle': 'Ingia kwenye akaunti yako',
    'or': 'AU',
    'continue_with_google': 'Endelea na Google',
    'dont_have_account': 'Hauna akaunti?',
    'sign_up': 'Jisajili',
    'password': 'Nenosiri',
    'forgot_password': 'Umesahau nenosiri?',
    'sign_in': 'Ingia',
    'new_password': 'Nenosiri Jipya',
    'confirm_password': 'Thibitisha Nenosiri',
    'update_password': 'Badili Nenosiri',
    'chat_placeholder': 'Andika ujumbe...',
    'send': 'Tuma',
    'food': 'Chakula',
    'grocery': 'Sokoni',
    'pharmacy': 'Duka la Dawa',
    'ecommerce': 'Maduka',
    'taxi': 'Teksi',
    'parcel': 'Vifurushi',
    'salons': 'Saluni',
    'hotels': 'Hoteli',
    'welcome': 'Karibu',
    'businesses': 'Biashara',
    'products': 'Bidhaa',
    'search_placeholder': 'Tafuta bidhaa...',
    'invalid_email_or_password': 'Barua pepe au nenosiri si sahihi.',
    'auth_disabled_instructions': "Usajili wa barua pepe umezimwa. Tafadhali washa 'Email/Password' kwenye mipangilio yako ya Firebase Console.",
    'login_failed': 'Kuingia kumeshindikana. Tafadhali jaribu tena.',
    'signup_failed': 'Usajili umeshindikana. Tafadhali jaribu tena.',
    'passwords_dont_match': 'Manenosiri hayafanani!',
    'agree_to_terms_error': 'Tafadhali kubaliana na vigezo na masharti',
    'account_created_success': 'Akaunti imetengenezwa kwa mafanikio!',
    'registration_submitted': 'Maombi ya usajili yametumwa kwa ajili ya uhakiki!',
    'nearby_stores': 'Duka za Karibu',
    'see_all': 'Zote',
    'other_services': 'Huduma Nyingine',
    'popular_restaurants': 'Migahawa Maarufu',
    'popular_products': 'Bidhaa Maarufu',
    'view_all': 'Zote',
    'order': 'Agiza',
    'order_now': 'Agiza Sasa',
    'very_close': 'Karibu Sana',
    'close': 'Karibu',
    'far_bit': 'Mbali Kidogo',
    'far': 'Mbali',
    'extremely_far': 'Mbali Sana',
    'admin_control_panel': 'Jopo la Uongozi',
    'admin_overview': 'Mapitio',
    'admin_businesses': 'Biashara',
    'admin_products': 'Bidhaa',
    'admin_communities': 'Wanajumuiya',
    'admin_sales_feed': 'Mauzo',
    'admin_marketing': 'Masoko',
    'admin_broadcast': 'Matangazo',
    'admin_gross_volume': 'Jumla Mauzo',
    'admin_commission': 'Tume',
    'admin_fees': 'Gharama',
    'admin_total_sales': 'Jumla Oda',
    'admin_view_store': 'Tazama Duka',
    'admin_approve': 'Kubali',
    'admin_reject': 'Kataa',
    'admin_block': 'Zuia',
    'admin_delete': 'Futa',
    'admin_search_placeholder': 'Tafuta hapa...',
    'admin_inventory_oversight': 'Usimamizi wa Bidhaa',
    'admin_members_search_placeholder': 'Tafuta kwa jina au barua pepe...',
    'admin_total_members': 'Jumla ya Wanachama',
    'admin_identity': 'Utambulisho',
    'admin_role': 'Wajibu',
    'admin_status': 'Hali',
    'admin_interactions': 'Muingiliano',
    'admin_global_live_feed': 'Mlisho wa Mubashara',
    'admin_live_monitoring': 'Ufuatiliaji wa Moja kwa Moja',
    'admin_order_ref': 'Rejea ya Oda',
    'admin_merchant': 'Muuzaji',
    'admin_payment': 'Malipo',
    'admin_value': 'Thamani',
    'admin_manage_banners': 'Simamia Mabango',
    'admin_add_banner': 'Ongeza Bango',
    'admin_new_banner': 'Bango Jipya la Matangazo',
    'admin_title': 'Kichwa cha Habari',
    'admin_subtitle': 'Maelezo Mafupi',
    'admin_image_url': 'Kiungo cha Picha',
    'admin_save_banner': 'Hifadhi Bango',
    'admin_manage_coupons': 'Simamia Kuponi',
    'admin_add_coupon': 'Ongeza Kuponi',
    'admin_official_coupon': 'Kuponi Rasmi',
    'admin_off': 'Punguzo',
    'admin_broadcast_title': 'Matangazo ya Jumuiya',
    'admin_broadcast_subtitle': 'Wafikishie ujumbe watumiaji wote mara moja.',
    'admin_alert_title': 'Kichwa cha Arifa',
    'admin_alert_content': 'Maelezo ya Arifa',
    'admin_initiate_broadcast': 'Anza Kutangaza',
    'admin_settings': 'Mipangilio',
    'admin_settings_business_info': 'Taarifa za Biashara',
    'admin_settings_payment': 'Malipo',
    'admin_settings_vendor': 'Wauzaji',
    'admin_settings_order': 'Oda',
    'admin_settings_refund': 'Utoaji wa Pesa',
    'admin_settings_deliveryman': 'Wajumbe wako',
    'admin_settings_customer': 'Wateja',
    'admin_settings_maintenance_mode': 'Mfumo wa Matengenezo',
    'admin_settings_basic_info': 'Maelezo ya Msingi',
    'admin_settings_business_name': 'Jina la Biashara',
    'admin_settings_upload_logo': 'Weka Logo',
    'admin_settings_upload_favicon': 'Weka Favicon',
    'admin_settings_save_information': 'Hifadhi Maelezo',
    'admin_settings_general_setup': 'Mipangilio ya Jumla',
    'admin_settings_time_setup': 'Mipangilio ya Muda',
    'admin_settings_currency_setup': 'Mipangilio ya Sarafu',
    'admin_settings_business_model': 'Mfumo wa Biashara',
    'admin_settings_vendor_general_setup': 'Mipangilio ya Jumla',
    'admin_settings_vendor_general_desc': 'Simamia mipangilio ya kimsingi inayodhibiti jinsi wauzaji wanavyofanya kazi kwenye jukwaa lako.',
    'admin_settings_vendor_cancel_order': 'Je, Muuzaji anaweza Kufuta Oda?',
    'admin_settings_vendor_self_reg': 'Kujisajili kwa Muuzaji',
    'admin_settings_vendor_gallery': 'Jalada la Bidhaa',
    'admin_settings_vendor_access_prods': 'Kufikia bidhaa zote',
    'admin_settings_vendor_can_reply': 'Muuzaji anaweza kujibu Maoni',
    'admin_settings_vendor_approval': 'Inahitaji Idhini Kwa',
    'admin_settings_vendor_approval_desc': 'Ikiwashwa, bidhaa itahitaji idhini ya admin kabla ya kuonekana kwa upande wa mtumiaji.',
    'admin_settings_vendor_add_prod': 'Ongeza Bidhaa Mpya',
    'admin_settings_vendor_edit_prod': 'Badilisha Bidhaa Iliyopo',
    'admin_settings_vendor_cash_ctrl': 'Udhibiti wa Pesa Mkononi',
    'admin_settings_vendor_cash_desc': 'Sanidi makusanyo yako ya pesa kutoka hapa',
    'admin_settings_vendor_cash_overflow': 'Ziada ya Pesa Mkononi',
    'admin_settings_vendor_max_cash': 'Kiwango cha Juu cha Pesa Mkononi',
    'admin_settings_vendor_min_pay': 'Kiwango cha Chini cha Kulipa',
    'admin_settings_order_type': 'Aina ya Oda',
    'admin_settings_order_type_desc': 'Njia ambayo mteja anaagiza chakula chake',
    'admin_settings_home_delivery': 'Usafirishaji wa Nyumbani',
    'admin_settings_takeaway': 'Chukua Mwenyewe (Takeaway)',
    'admin_settings_scheduled_order': 'Oda Iliyopangwa',
    'admin_settings_time_interval': 'Muda wa Usafirishaji uliopangwa',
    'admin_settings_free_delivery': 'Mipangilio ya Usafirishaji wa Bure',
    'admin_settings_free_delivery_desc': 'Washa chaguo hili ili kuwapa wateja ofa ya kusafirishiwa bure.',
    'admin_settings_extra_packaging': 'Washa Gharama ya Ufungaji wa Ziada',
    'admin_settings_extra_packaging_desc': 'Huongeza ada ya ziada kwa oda zinazohitaji ulinzi zaidi, kama vile vitu vinavyovunjika.',
    'admin_settings_other_setup': 'Mipangilio Mingine',
    'admin_settings_prescription_order': 'Agiza kwa Maelekezo (Prescription)',
    'admin_settings_delivery_verification': 'Uhakiki wa uwasilishaji wa oda',
    'admin_settings_confirm_order': 'Nani Atathibitisha Oda',
    'admin_settings_cancellation_msg': 'Sanidi Ujumbe wa Kufuta Oda',
    'admin_settings_cancellation_msg_desc': 'Sanidi ujumbe wa kufuta oda hapa ili kuwaruhusu wateja kuchagua sababu wanapofuta oda',
    'admin_settings_cancellation_reason': 'Sababu ya Kufuta Oda',
    'admin_settings_user_type': 'Aina ya Mtumiaji',
    'admin_settings_reason_list': 'Orodha ya sababu za kufuta oda',
    'admin_settings_refund_mode': 'Mfumo wa Ombi la Rejesho la Pesa',
    'admin_settings_refund_mode_desc': 'Wateja hawawezi kuomba rejesho la pesa ikiwa Admin hajaainisha sababu ya rejesho. Ni lazima Admin atoe sababu ya rejesho.',
    'admin_settings_add_refund_reason': 'Ongeza Sababu ya Rejesho',
    'admin_settings_refund_reason': 'Sababu ya Rejesho',
    'admin_settings_refund_reason_list': 'Orodha ya Sababu za Rejesho',
  },
  ar: {
    'my_orders': 'طلباتي',
    'edit_profile': 'تعديل الملف الشخصي',
    'chat': 'دردشة',
    'address': 'العنوان',
    'change_password': 'تغيير كلمة المرور',
    'change_language': 'تغيير اللغة',
    'sign_out': 'تسجيل الخروج',
    'active_orders': 'الطلبات النشطة',
    'previous_orders': 'الطلبات السابقة',
    'order_id': 'رقم الطلب',
    'total': 'الإجمالي',
    'see_details': 'عرض التفاصيل',
    'back_to_home': 'العودة للرئيسية',
    'back_to_orders': 'العودة للطلبات',
    'order_details': 'تفاصيل الطلب',
    'order_type': 'نوع الطلب',
    'delivery_time': 'وقت التسليم',
    'takeaway_time': 'وقت الاستلام',
    'subtotal': 'المجموع الفرعي',
    'discount': 'الخصم',
    'delivery_charge': 'رسوم التوصيل',
    'print_invoice': 'طباعة الفاتورة',
    'pay_now': 'ادفع الآن',
    'status': 'الحالة',
    'method': 'الطريقة',
    'payment_info': 'معلومات الدفع',
    'delivery_address': 'عنوان التوصيل',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'email': 'البريد الإلكتروني',
    'phone': 'رقم الهاتف',
    'joined': 'انضم في',
    'personal_info': 'المعلومات الشخصية',
    'edit': 'تعديل',
    'welcome_back': 'مرحباً بعودتك!',
    'sign_in_subtitle': 'تسجيل الدخول إلى حسابك',
    'or': 'أو',
    'continue_with_google': 'المتابعة باستخدام جوجل',
    'dont_have_account': 'ليس لديك حساب؟',
    'sign_up': 'إنشاء حساب',
    'password': 'كلمة المرور',
    'forgot_password': 'نسيت كلمة المرور؟',
    'sign_in': 'تسجيل الدخول',
    'new_password': 'كلمة مرور جديدة',
    'confirm_password': 'تأكيد كلمة المرور',
    'update_password': 'تحديث كلمة المرور',
    'chat_placeholder': 'اكتب رسالة...',
    'send': 'إرسال',
    'food': 'طعام',
    'grocery': 'بقالة',
    'pharmacy': 'صيدلية',
    'ecommerce': 'تجارة إلكترونية',
    'taxi': 'تاكسي',
    'parcel': 'طرود',
    'salons': 'صالونات',
    'hotels': 'فنادق',
    'welcome': 'مرحباً',
    'businesses': 'الأعمال',
    'products': 'المنتجات',
    'search_placeholder': 'ابحث عن عناصر...',
    'invalid_email_or_password': 'البريد الإلكتروني أو كلمة المرور غير صالحة.',
    'auth_disabled_instructions': 'تم تعطيل التسجيل عبر البريد الإلكتروني حالياً.',
    'login_failed': 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
    'signup_failed': 'فشل التسجيل. يرجى المحاولة مرة أخرى.',
    'passwords_dont_match': 'كلمات المرور غير متطابقة!',
    'agree_to_terms_error': 'يرجى الموافقة على الشروط والأحكام',
    'account_created_success': 'تم إنشاء الحساب بنجاح!',
    'registration_submitted': 'تم تقديم طلب التسجيل للمراجعة!',
    'nearby_stores': 'متاجر قريبة',
    'see_all': 'الكل',
    'other_services': 'خدمات أخرى',
    'popular_restaurants': 'مطاعم شهيرة',
    'popular_products': 'منتجات شهيرة',
    'view_all': 'عرض الكل',
    'order': 'طلب',
    'order_now': 'اطلب الآن',
    'admin_control_panel': 'لوحة التحكم',
    'admin_overview': 'نظرة عامة',
    'admin_businesses': 'الأعمال',
    'admin_products': 'المنتجات',
    'admin_communities': 'المجتمعات',
    'admin_sales_feed': 'موجز المبيعات',
    'admin_marketing': 'التسويق',
    'admin_broadcast': 'بث',
    'admin_gross_volume': 'إجمالي الحجم',
    'admin_commission': 'العمولة المقدرة',
    'admin_fees': 'الرسوم المحسوبة',
    'admin_total_sales': 'إجمالي المبيعات',
    'admin_view_store': 'عرض المتجر',
    'admin_approve': 'موافقة',
    'admin_reject': 'رفض',
    'admin_block': 'حظر',
    'admin_delete': 'حذف',
    'admin_search_placeholder': 'ابحث هنا...',
    'admin_inventory_oversight': 'الرقابة على المخزون',
    'admin_members_search_placeholder': 'البحث عن الأعضاء بالاسم أو البريد...',
    'admin_total_members': 'إجمالي الأعضاء',
    'admin_identity': 'الهوية',
    'admin_role': 'الدور',
    'admin_status': 'الحالة',
    'admin_interactions': 'التفاعلات',
    'admin_global_live_feed': 'موجز مباشر عالمي',
    'admin_live_monitoring': 'مراقبة مباشرة',
    'admin_order_ref': 'مرجع الطلب',
    'admin_merchant': 'التاجر',
    'admin_payment': 'الدفع',
    'admin_value': 'القيمة',
    'admin_manage_banners': 'إدارة لافتات العرض',
    'admin_add_banner': 'إضافة لافتة',
    'admin_new_banner': 'لافتة ترويجية جديدة',
    'admin_title': 'العنوان',
    'admin_subtitle': 'العنوان الفرعي',
    'admin_image_url': 'رابط الصورة',
    'admin_save_banner': 'حفظ اللافتة',
    'admin_manage_coupons': 'إدارة الكوبونات',
    'admin_add_coupon': 'إضافة كوبون',
    'admin_official_coupon': 'كوبون رسمي',
    'admin_off': 'خصم',
    'admin_broadcast_title': 'بث عالمي',
    'admin_broadcast_subtitle': 'تواصل مع كل مستخدم في مجتمعك فوراً.',
    'admin_alert_title': 'عنوان التنبيه',
    'admin_alert_content': 'محتوى التنبيه',
    'admin_initiate_broadcast': 'بدء البث',
    'admin_settings': 'الإعدادات',
    'admin_settings_business_info': 'معلومات العمل',
    'admin_settings_payment': 'الدفع',
    'admin_settings_vendor': 'البائع',
    'admin_settings_order': 'الطلب',
    'admin_settings_refund': 'رد الأموال',
    'admin_settings_deliveryman': 'عامل التوصيل',
    'admin_settings_customer': 'الزبون',
    'admin_settings_maintenance_mode': 'وضع الصيانة',
    'admin_settings_basic_info': 'معلومات أساسية',
    'admin_settings_business_name': 'اسم العمل',
    'admin_settings_upload_logo': 'تحميل الشعار',
    'admin_settings_upload_favicon': 'تحميل أيقونة المفضلة',
    'admin_settings_save_information': 'حفظ المعلومات',
    'admin_settings_general_setup': 'الإعداد العام',
    'admin_settings_time_setup': 'إعداد الوقت',
    'admin_settings_currency_setup': 'إعداد العملة',
    'admin_settings_business_model': 'نموذج العمل',
    'admin_settings_vendor_general_setup': 'الإعداد العام',
    'admin_settings_vendor_general_desc': 'إدارة الإعدادات الأساسية التي تتحكم في كيفية عمل البائعين في منصتك.',
    'admin_settings_vendor_cancel_order': 'هل يمكن للبائع إلغاء الطلب؟',
    'admin_settings_vendor_self_reg': 'التسجيل الذاتي للبائع',
    'admin_settings_vendor_gallery': 'معرض المنتجات',
    'admin_settings_vendor_access_prods': 'الوصول إلى جميع المنتجات',
    'admin_settings_vendor_can_reply': 'يمكن للبائع الرد على التقييم',
    'admin_settings_vendor_approval': 'تحتاج إلى موافقة لـ',
    'admin_settings_vendor_approval_desc': 'إذا تم تمكين هذا الخيار ، فسيطلب موافقة المسؤول ليتم عرض المنتجات على جانب المستخدم.',
    'admin_settings_vendor_add_prod': 'إضافة منتج جديد',
    'admin_settings_vendor_edit_prod': 'تحديث المنتج الحالي',
    'admin_settings_vendor_cash_ctrl': 'ضوابط النقد في اليد',
    'admin_settings_vendor_cash_desc': 'قم بإعداد تحصيل النقود من هنا',
    'admin_settings_vendor_cash_overflow': 'تجاوز النقد في اليد',
    'admin_settings_vendor_max_cash': 'الحد الأقصى للمبلغ النقدي في اليد',
    'admin_settings_vendor_min_pay': 'الحد الأدنى للمبلغ للدفع',
    'admin_settings_order_type': 'نوع الطلب',
    'admin_settings_order_type_desc': 'بأي طريقة يطلب العميل طعامه',
    'admin_settings_home_delivery': 'توصيل للمنزل',
    'admin_settings_takeaway': 'استلام من المتجر',
    'admin_settings_scheduled_order': 'طلب مجدول',
    'admin_settings_time_interval': 'الفترة الزمنية للتوصيل المجدول',
    'admin_settings_free_delivery': 'إعداد التوصيل المجاني',
    'admin_settings_free_delivery_desc': 'قم بتمكين هذا الخيار لمنح العملاء عرض توصيل مجاني.',
    'admin_settings_extra_packaging': 'تمكين رسوم التغليف الإضافية',
    'admin_settings_extra_packaging_desc': 'يضيف رسومًا إضافية للطلبات التي تحتاج إلى حماية إضافية ، مثل العناصر الهشة.',
    'admin_settings_other_setup': 'إعدادات أخرى',
    'admin_settings_prescription_order': 'تقديم طلب عن طريق وصفة طبية',
    'admin_settings_delivery_verification': 'التحقق من توصيل الطلب',
    'admin_settings_confirm_order': 'من سيوكد الطلب',
    'admin_settings_cancellation_msg': 'إعداد رسائل إلغاء الطلب',
    'admin_settings_cancellation_msg_desc': 'قم بإعداد رسائل الإلغاء هنا للسماح للعملاء باختيار سبب عند إلغاء الطلب',
    'admin_settings_cancellation_reason': 'سبب إلغاء الطلب',
    'admin_settings_user_type': 'نوع المستخدم',
    'admin_settings_reason_list': 'قائمة أسباب إلغاء الطلب',
    'admin_settings_refund_mode': 'وضع طلب استرداد الأموال',
    'admin_settings_refund_mode_desc': 'لا يمكن للعملاء طلب استرداد الأموال إذا لم يحدد المسؤول سببًا لاسترداد الأموال. يجب على المسؤول تقديم سبب استرداد الأموال.',
    'admin_settings_add_refund_reason': 'إضافة سبب استرداد الأموال',
    'admin_settings_refund_reason': 'سبب استرداد الأموال',
    'admin_settings_refund_reason_list': 'قائمة أسباب استرداد الأموال',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'sw';
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} className={isRTL ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
